services:
    vehicletransformer:
        image:
    linetransformer:
        image:
    stoptransformer:
        image:
    activemqfeeder:
        image:
    trafficdatawebserver:
        image:
        
