# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.
FROM anapsix/alpine-java

RUN mkdir /app
ADD run-transformer.sh /app
CMD ["/app/run-transformer.sh"]
