services:
    zookeeper:
        image: wurstmeister/zookeeper
    kafka:
        image:
    activemq:
        image:
    vehicletransformer:
        image:
    linetransformer:
        image:
    stoptransformer:
        image:
    activemqfeeder:
        image:
    trafficdatawebserver:
        image:
        
